# This is a basic workflow to help you get started with Actions
name: Deploy en S3

on:
  push:
    branches:
      - master
  # To enable manual runs
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CI: false
  AWS_S3_BUCKET: 'produccion-proyectofinal'
  AWS_REGION: 'us-east-1'
  SOURCE_DIR: 'build'      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  Subida_a_S3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install application dependencies
      - name: Instala dependencias
        run: |
          npm install
      # build and test the apps
      - name: buildeo
        run: |
          npm run build
          #npm test

      #- name: Install dependencies
        #run: yarn

      #- name: Build
        #run: yarn build

      #- name: Subir a S3
        #uses: reggionick/s3-deploy@v3
        #with:
          #folder: build
          #bucket: produccion-proyectofinal
          #bucket-region: us-east-1
          #dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          #invalidation: /
          #delete-removed: true
          #no-cache: true
          #private: true

      - name: Subir a S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
